server.port=8080
demo.jwt.secret=live-demo-jwt-secret-key-32-chars-long
demo.paseto.local-key=live-demo-paseto-local-key-32-bytes
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**
logging.level.com.sgedts.demopaseto=INFO
